title: Sarah Finch (Fillwock) # your name (or website title) here
logo: "/images/profile-pic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Ph.D., Computer Science (2024)</b>
  <br>
  <b>Emory University</b>
  <br><br>
  My research interests are in Conversational AI. 
  I have explored many facets of conversational systems, 
  including the development and deployment of a personal-experience-oriented dialogue system for large-scale usage 
  and improving the evaluation of dialogue models through fine-grained behavior analysis. 
  My most recent and ongoing works focus on improving social understanding and commonsense reasoning in dialogue models in the era of Large Language Models. 
  <br><br>
  <em>Awards:</em>
  <br>
  Amazon Alexa Prize 3 Winner
  <br>
  Emory George W. Woodruff Fellowship
  <br>
  Emory Schoettle Research Award
  <br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
